In [2]:
import numpy as np
import scipy.linalg as la

import session_info
session_info.show()

## Session 1 

### Creation of Vectors and Matrices

1. Create a row vector of natural numbers of size 4.

In [10]:
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

2. Create a 2 x 2 matrix of all zeros, all ones, all with a value of 4 and all with random values.

In [18]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [14]:
one = np.ones((2,2))
one

array([[1., 1.],
       [1., 1.]])

In [20]:
four = np.full((2,2),4)
four

array([[4, 4],
       [4, 4]])

In [25]:
rand = np.random.rand(2,2)
rand

array([[0.20653398, 0.53553677],
       [0.77571288, 0.09910009]])

### Vector and Matrix Operations 


3. Find the magnitude/ L1 and L2 norm of the vector [4,6] and state which has a highest value.


In [26]:
x = np.array([4,6])
y = np.linalg.norm(x, ord=1)
y

10.0

In [27]:
y1 = np.linalg.norm(x,ord=2)
y1

7.211102550927978

In [28]:
if y>y1:
    print("y is greater than y1")
else:
    print("y1 is greater than y")

y is greater than y1


### Scalar and Vector Projections
5. Find the scalar and vector projections of the vector  u = 8i + 6j on vector v = i - 7j


In [29]:
u = np.array([8,6])
v = np.array([1,-7])

In [30]:
scalar = np.dot(u,v)/np.linalg.norm(v)
vector = v*scalar/np.linalg.norm(v)

In [31]:
print(f"the value of scalar {scalar}")
print(f"the value of vector {vector}")

the value of scalar -4.808326112068523
the value of vector [-0.68  4.76]


### Session 2



In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL  import Image
import scipy
from skimage import data
from numpy import *


#### Q5. Find the Determinant for the following matrix. If B is a scaled matrix computed by scaling the matrix A, find the scale factor associated.

In [34]:
A = np.array([
[10, 12, 13],
[14, 15, 16],
[17, 18, 19]])

In [35]:
B=np.array([
[30, 36, 39],
[42, 45, 48],
[51, 54, 57]])

In [48]:
a1 = np.linalg.det(A)
b1 = np.linalg.det(B)
a1,b1

(47.00000000000008, 0.0)

In [52]:
scaled_matrix = np.dot(B,A)

In [53]:
scaled_matrix

array([[17,  8, 18],
       [17,  8, 18],
       [17,  8, 18]])

#### Q6: If Matrix A and B are given, then find the matrix X from AX=B. 

In [49]:
A = np.array([
[11, 12, 13],
[11, 15, 14],
[17, 11, 19]])

B = np.array([[1, -1 , 1],[1, -1 , 1],[1, -1 , 1]])

In [50]:
solution = np.linalg.solve(A,B)

In [51]:
solution

array([[ 0.40425532, -0.40425532,  0.40425532],
       [ 0.12765957, -0.12765957,  0.12765957],
       [-0.38297872,  0.38297872, -0.38297872]])

### System of Linear equations

#### Q7. Solve the following system and find x and y $$\begin{pmatrix}
1&2\\
3&4
\end{pmatrix} \begin{pmatrix}
x\\
y
\end{pmatrix} =\begin{pmatrix}
-1\\
1
\end{pmatrix}$$

In [67]:
import sympy as sym

In [69]:
sym.init_printing()
x,y = sym.symbols('x,y')
sol = sym.solve([
    x + 2*y - -1,
    3*x + 4*y - 1
],[x,y])
sol

### Gram-Schmidt Process

#### Q8.Convert the following matrix to an orthogonal matrix using Gram Schmidt Process?
\begin{align}
B = \begin{bmatrix}
12 & 13 & 14\\
13 & 14 & 15\\
15 & 16 & 13
\end{bmatrix}
\end{align}

#hint: To check if a given matrix is orthogonal, first find the transpose of that matrix. 
#Then, multiply the given matrix with the transpose. 
#Now, if the product is an identity matrix, the given matrix is orthogonal, otherwise, not.

In [54]:
B = np.array([[12,13,14],[13,14,15],[15,16,13]])

In [66]:
def gram_smit(B):
    Q,R = np.linalg.qr(B)
    return Q, R
gram_smit(B)

(array([[-0.51735674,  0.66830212,  0.53452248],
        [-0.5604698 ,  0.20740411, -0.80178373],
        [-0.64669592, -0.71439192,  0.26726124]]),
 array([[-23.19482701, -24.91934946, -24.05708824],
        [  0.        ,   0.1613143 ,   3.18019629],
        [  0.        ,   0.        ,  -1.06904497]]))

### Eigen values 

#### Q9.Find eigen values and eigen vectors for 

\begin{align}
A = \begin{bmatrix}
2 & -1 & 0\\
-1 & 2 & -1\\
0 & -1 & 2
\end{bmatrix}
\end{align}

In [37]:
matrix = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

In [38]:
eignvalue, eignvector = np.linalg.eig(matrix)

In [43]:
eignvalue,eignvector

(array([3.41421356, 2.        , 0.58578644]),
 array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
        [ 7.07106781e-01,  4.19803081e-16,  7.07106781e-01],
        [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))