- Introduction

- Vecotrs (Row and Column vectors)

- Vector properties and operations

- Matrix properties and operations

- Linear Independence


The python package to use for all the linear algebra concepts here is numpy and scipy - Scientific Python which has a dedicated linear algebra module for most of the operations in linear algebra. 

In [ ]:
import numpy as np
import scipy.linalg as la

Numpy array can be used to create a vector - both row and column vectors.

### Row Vector
\begin{align}
    a &= \begin{bmatrix}
           1&2&3&4&5&6 \\
           \end{bmatrix}
  \end{align}

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])  # 6 dimesional vector 
print(a)

[1 2 3 4 5 6]


The shape and type of the vectors can be checked using array_name.shape and type(array_name)

In [5]:
a.shape

(6,)

In [6]:
type(a)

numpy.ndarray

In [7]:
a.transpose()

array([1, 2, 3, 4, 5, 6])

In [8]:
a.dot(a.transpose())  # dot product of a with a 

91

As seen from above, the shape is 6 since there are 6 elements and the type is an n-dimensional numpy array.

### Column Vector
 \begin{align}
    a &= \begin{bmatrix}
           1 \\
           2 \\
           3 \\
           4 \\
           5 \\
           6 \\
         \end{bmatrix}
  \end{align}

In [10]:
a.shape

(6,)

In [11]:
a

array([1, 2, 3, 4, 5, 6])

In [12]:
# we can force a to be a column vector
a.shape=(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
type(a)

numpy.ndarray

In [14]:
b=a.transpose()
print(b)

[[1 2 3 4 5 6]]


In [29]:
a.shape=(6, 1)

In [30]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
# This dot product can be thought of as product of two matrices
# a is matirx of order 1 by 6( row vector)
# b is a matrix of order 6 by 1( column vector)
a.dot(b) # Resultant matrix of order 6 by 6

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

## Addition substraction scalar multiplication of vectors

In [32]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
c = a + b # Addition of two vector
d = a-b   # Substraction of vctors
x = 2*a   # Scalar multiplication
print("The addition is",c)
print("The Substraction is",d)
print("The scalar multiplication is",x)

The addition is [3 6 9]
The Substraction is [-1 -2 -3]
The scalar multiplication is [2 4 6]


### Matrix Creation and manipulation

In [33]:
# Create a matrix with all zeros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# Create a 3 x 3matrix with all ones
b = np.ones((3,3))
print (b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# Create a 3 x 3 matrix with the same constant 1.1
c = np.full((3,3), 1.1)
print (c)

[[1.1 1.1 1.1]
 [1.1 1.1 1.1]
 [1.1 1.1 1.1]]


In [ ]:
# Create a 3 x 3 matrix  with random values
d = np.random.random((3,3))
print (d)

In [36]:
# Create a matrix with all elements specified. Each list is a row.
A=np.array([[1,2],[3,4],[5,6]])
print (A)
A.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [37]:
type(A)

numpy.ndarray

Higher dimensional matrix

In [38]:
# Create 2 x 4 matrix (2 rows and 4 columns )
B=np.array([[1, 2, 3, 4], [11, 12, 13, 14]])
B

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

The matrix B above is a rectangular matrix and of higher dimension. Let us check the shape of the matrix above.

In [39]:
B.shape

(2, 4)

#### Transpose of a matrix

In [40]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# Transpose a matrix 
A.T

array([[1, 3, 5],
       [2, 4, 6]])

The matrix changes shape such that the rows become columns and columns become rows.

# Vector and Matrix Operations 


### Magnitude of a vector / Vector norm

The length of vector is called the magnitude / norm of the vector. 

There are Three norms - $L_1$ and $L_2$ and $L_\infty$ norms.

$L_1$ Norm - computes Manhattan distance $||u||_1 = |x_1|+|x_2|$

$L_2$ Norm - computes Euclidean distance. By default, it uses the L2 norm. $||u||_2=\sqrt(x_1^2+x_2^2)$ 

$L_\infty$ Norm - computes Chebeyshev norm  is also known as chessboard distance, since in the game of chess the minimum number of moves needed by a king to go from one square on a chessboard to another equals the Chebyshev distance between the centers of the squares
$||u||_\infty = max $\{|x_1|,|x_2|}

For $L_1$ norm, the argument, ord = 1 should be passed. 


In [42]:
u  = np.array([1,2,3,4,5])

In [43]:
u

array([1, 2, 3, 4, 5])

In [55]:
math.sqrt(55.0)

7.416198487095663

In [54]:
5.477225575051661 * 5.477225575051661 + 25

55.0

In [44]:
np.linalg.norm(u) # Euclidean Distance L_2 norm

7.416198487095663

In [45]:
np.linalg.norm(u, ord=2)

7.416198487095663

In [46]:
np.linalg.norm(u, ord=1) # Manhattan Distance

15.0

In [56]:
np.linalg.norm(u, ord=np.inf)

5.0

In [57]:
from scipy.spatial import distance

In [58]:
distance.chebyshev([1, 0, 0], [0, 1, 0]) # max{|1-0|,|0-1|,|0-0|}

1

## Matrix/Vector Algebra
All the basic arithmetic operations can be performed on vectors of same length. 

Addition and Subtraction: 
Both addition and subtraction can be performed using numpy. It is elementwise addition and subtraction ('+' & '-')

Vector Multiplication and Division: 
Both multiplication and division can be performed using numpy '*' and '/'.

In [59]:
A=np.array([[1,2],[3,4],[5,6]]) # Matrix of order 2 by 2
B=np.array([[11,12],[13,14],[15,16]]) # Matrix of order 2 by 2

In [60]:
# Addition:
C = A + B
C   # matrix of order 2 by 2

array([[12, 14],
       [16, 18],
       [20, 22]])

In [61]:
# Subtraction:
C= A-B
C

array([[-10, -10],
       [-10, -10],
       [-10, -10]])

In [64]:
print(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [13 14]
 [15 16]]


In [62]:
# Multiplication ( Component wise Multiplication-Hardmard Product)
C = A * B
C

array([[11, 24],
       [39, 56],
       [75, 96]])

In [65]:
import numpy as np
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[11,12],[13,14],[15,16]])
A[0,0]/B[0,0]

0.09090909090909091

In [66]:
# Division is elementwise 
C=A/B
C

array([[0.09090909, 0.16666667],
       [0.23076923, 0.28571429],
       [0.33333333, 0.375     ]])

In [67]:
A*B # element wise called Hardmard product

array([[11, 24],
       [39, 56],
       [75, 96]])

## Dot product

For 1-d arrays, the dot product/ inner product is defined using np.dot function.

For 2-D arrays, it is matrix multiplication which is done using matmul or a @ b.

If a scalar is multiplied with the vector, then it is equivalent to multiplying the scalar with all the elements of vector or matrix and using np.multiply (a, b) or a * b is preferred.

In [68]:
a = [[1, 2], [3, 4]]     
np.array(a)


array([[1, 2],
       [3, 4]])

In [69]:
b = [[5, 6], [7, 8]]
np.array(b)

array([[5, 6],
       [7, 8]])

In [73]:
print(a)
print(b)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [74]:
# matrix-matrix multiplication
np.dot(a, b)         #[[1*5+2*7, 1*6+2*8], 
                     # [3*5+4*7, 3*6+4*8]]

array([[19, 22],
       [43, 50]])

# Cosine Similarity
$cos(\theta)= \frac{u.v}{||u||||v||}$

In [75]:
a = np.array([12000,34])
b = np.array([174,1500000])
cos_theta = np.dot(a,b)/[np.linalg.norm(a)*np.linalg.norm(b)] # Euclidean Distance]
cos_theta

array([0.00294932])

In [76]:
a

array([12000,    34])

In [78]:
b

array([    174, 1500000])

In [79]:
np.dot(a,b)

53088000

In [84]:
np.linalg.norm(a)

12000.048166569999

In [86]:
print(math.sqrt(12000 * 12000 + 34 * 34 ))

12000.048166569999


In [81]:
np.linalg.norm(b)

1500000.010092

In [87]:
print(math.sqrt(174 * 174 + 1500000 * 1500000))

1500000.010092


# Multiplication Error

In [ ]:
# matrix-matrix multiplication
np.dot(A,B)

In [ ]:
# matrix-matrix multiplication 
# size should match!
np.dot(B,A)

#A.B is not the same as B.A

In [ ]:
# coefficient matrix A and a vector b, The result is a vector
A=np.array([[1, 2],[3, 4]])
b=np.array([1, 2])

In [ ]:
np.dot(A,b)

### Scalar and Vector Projections
- If u and v are two vectors then we define $proj_v(u)=\frac{u.v}{||v||}$
- We also define vector projection as 
$proj_v(u) = \frac{u.v}{||v||^2}{v}$

In [ ]:
# Scalar Projection of u on v
u = np.array([6, 7])
v = np.array([5, -12])

In [ ]:
u*v

In [ ]:
np.dot(u,v)

In [ ]:
sc_proj = np.dot(u, v) / np.linalg.norm(v)   # u.v/||v||
sc_proj

In [ ]:
# Vector projection of u on v
vec_proj = (v * sc_proj)/ np.linalg.norm(v)   # (v * (np.dot(u,v)/np.linalg.norm(v)) / np.linalg.norm(v)  
vec_proj

In [ ]:
# Vector Projection (vector * scalar projection) / v norm

u = np.array([1, 2, 3])   # vector u 
v = np.array([5, 6, 2])   # vector v: 
  
vec_proj = v * (np.dot(u,v)/np.linalg.norm(v)) / np.linalg.norm(v)

print("Projection of Vector u on Vector v is: ", vec_proj) 


### Identity Matrix

In [ ]:
# identity matrix 
eye3 = np.eye(3)
eye3

### Linear Combination (Weighted sum of two vectors)

$$
\vec{u}=
\begin{bmatrix}
    1 \\\\
    3
\end{bmatrix}
$$
and

$$
\vec{v}=
\begin{bmatrix}
    2 \\\\
    1
\end{bmatrix}
$$ 
The linear combination of $\vec{u}$ and $\vec{v}$ is

$$
a\vec{u}+b\vec{v}= a
\begin{bmatrix}
    1 \\\\
    3
\end{bmatrix} + b\begin{bmatrix}
    2 \\\\
    1
\end{bmatrix}
$$
if $a=2$ and $b=1$:

$$
2\vec{u}+\vec{v}= 2
\begin{bmatrix}
    1 \\\\
    3
\end{bmatrix} +
\begin{bmatrix}
    2 \\\\
    1
\end{bmatrix} =
\begin{bmatrix}
    2 \cdot 1 + 2 \\\\
    2 \cdot 3 + 1
\end{bmatrix} =
\begin{bmatrix}
    4 \\\\
    7
\end{bmatrix}
$$

### Linear Independence
Check for linear combination of vectors. If it zero, then the set of vectors is linearly independent.

The no. of linearly independent columns will determine the no. of solutions.

Direction of two linearly dependent vectors is the same.

Determine whether the vectors are linearly independent of each other to see if the vectors form a basis,

or to determine how many independent equations there are, 

or to determine how many independent reactions there are.

The set S =$\{v_1, v_2, v_3\}$ of vectors in R3 is linearly independent if the only solution of

$c_1v_1 + c_2v_2 + c_3v_3 = 0 $
is $c_1, c_2, c_3 = 0 $



In [ ]:
u = np.array([[1],[0]])
v= np.array([[0],[1]])
w = np.array([[2], [1]])

In [ ]:
lin_combination = 2*u + 1*v
lin_combination         # w is a linear combination of u and v [ w is in the span of u and v]

## Types of Matrices

In [ ]:
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

In [ ]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

In [ ]:
# define square matrix
M = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(M)

In [ ]:
# lower triangular matrix
lower = tril(M)
print(lower)

In [ ]:
# upper triangular matrix
upper = triu(M)
print(upper)

In [ ]:
# diagonal matrix
from numpy import array
from numpy import diag

In [ ]:
# define square matrix
M = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(M)

In [ ]:
# extract diagonal vector
d = diag(M)
print(d)

In [ ]:
# create diagonal matrix from vector
D = diag(d)
print(D)

In [ ]:
from numpy import identity

In [ ]:
I = identity(3)
print(I)

In [ ]:
from numpy import array
from numpy.linalg import inv

- A matrix Q is called orthogonal if $ Q.Q^T= I$  or $Q^T= Q^{-1}$

In [ ]:
# define orthogonal matrix
Q = array([ 
[2,-2, 1],
[1, 2, 2],
[2,-1, -2]])
print(Q)

In [ ]:
# inverse equivalence
V = inv(Q)
#print(Q.T)
print(V)

In [ ]:
# identity equivalence
I = Q.dot(Q.T)
print(I)

In [ ]:
# define orthogonal matrix
Q = array([ 
[2,-2],
[1, 2]])
print(Q)

In [ ]:
inv(Q)

In [ ]:
Q.T