In [1]:
import numpy as np

# Numpy Arrays

In [2]:
arr_str = ["Mercedes", "BMW", "Audi", "Ferrari", "Tesla"]
arr_num = [5, 4, 6, 7, 3]

In [3]:
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

In [4]:
print("Numpy Array (arr_str)", np_arr_str)
print("Numpy Array (arr_num)", np_arr_num)

Numpy Array (arr_str) ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num) [5 4 6 7 3]


In [5]:
# printing the data type of lists
print("Data type of arr_str : ", type(arr_str))
print("Data type of arr_num : ", type(arr_num))

# printing the data type after conversion of lists to array
print("Data type of np_arr_str : ", type(np_arr_str))
print("Data type of np_arr_num : ", type(np_arr_num))

Data type of arr_str :  <class 'list'>
Data type of arr_num :  <class 'list'>
Data type of np_arr_str :  <class 'numpy.ndarray'>
Data type of np_arr_num :  <class 'numpy.ndarray'>


In [6]:
# Creating a numpy array from tuple
tuple_a = (1, 2, 3, 5, 4)

np_arr_tup = np.array(tuple_a)

In [7]:
# print the types of numpy array and tuples
print("Data type of tuple_a : ", type(tuple_a))
print("Data type of np_arr_tup : ", type(np_arr_tup))

Data type of tuple_a :  <class 'tuple'>
Data type of np_arr_tup :  <class 'numpy.ndarray'>


In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("Data type of matrix : ", type(matrix))

Data type of matrix :  <class 'numpy.ndarray'>


# NUmpy Functions

In [11]:
list(range(0, 10))       # Conventional python list from range. It excludes last number. 10 in this case

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arr1 = np.arange(start = 0, stop = 10) # similar to lists from range in numpy. It also excludes last number
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2 = np.arange(0, 10)               # numpy range can be written in shorter form as
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr3 = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

Using np.linspace() function
    - The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.
    - It has the following parameters:
        1. start : start of interval range. By default start = 0
        2. stop  : end of interval range
        3. num   : No. of samples to generate. By default num = 50

In [15]:
matrix2 = np.linspace(
    0, 5
)   # by default 50 evenly spaced values will be generated between 0 and 5

matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [17]:
matrix3 = np.linspace(10, 20, 10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
print(type(matrix3))

<class 'numpy.ndarray'>


Using np.zeros()
- The np.zeros() is a function for creating a matrix and performimg matrix operations in NumPy
- It returns a matrix filled with zeros of the given shape
- It has the following parameters:
    1. shape : Number of rows and columns in the output matrix
    2. dtype: data type of the elements in the matrix, by default the value is set to float

In [20]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
matrix5 = np.zeros([4,5], dtype='int')
matrix5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Using np.ones()
- The np.ones() is another function for creating a matrix and performimg matrix operations in NumPy
- It returns a matrix of given shape and type, filled with ones
- It has the following parameters:
    1. shape : Number of rows and columns in the output matrix
    2. dtype: data type of the elements in the matrix, by default the value is set to float

In [25]:
matrix6 = np.ones([3,5],'int')
matrix6

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
matrix7 = np.ones([3,5],'int','F')
matrix7

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
matrix6[1,3] = 7
matrix7[1,3] = 7

In [30]:
matrix6

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 7, 1],
       [1, 1, 1, 1, 1]])

In [31]:
matrix7

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 7, 1],
       [1, 1, 1, 1, 1]])

In [32]:
matrix8 = np.ones([3,4,5])
matrix8

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [35]:
matrix9 = np.eye(5, dtype= 'int')
matrix9

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
rand_arr = np.random.randn(10)
rand_arr

array([ 1.38180363,  0.84267012,  0.52920002,  0.09943938,  0.74565158,
        0.41012692,  0.56176159,  0.62765829, -0.21942752, -0.90133633])

In [37]:
rand_arr > 0

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [39]:
rand_arr[rand_arr > 0]

array([1.38180363, 0.84267012, 0.52920002, 0.09943938, 0.74565158,
       0.41012692, 0.56176159, 0.62765829])

Reshape

In [42]:
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)

randint_matrix1

array([[4, 5, 5, 6, 3],
       [5, 8, 2, 4, 9]])

In [43]:
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)

randint_matrix2

array([[17, 13, 14, 19, 13],
       [17, 14, 10, 11, 16]])