In [42]:
import random
import numpy as np

In [ ]:
# Rosenblat's Perceptron included a way to adjust the weights and find the appropriate combinations to overcome the need to modify thresholds
# for each gate seperately, it used a bias term using which the tresholds in the neuron can be modified to implement multiple boolean functions
# in one code

In [59]:
step_function = lambda x: 0 if x < 100 else 1         # step function with threshold of 100. Any thing below is 0

# AND Gate
training_data = [
    (np.array([0, 0, 1]), 0),
    (np.array([0, 1, 1]), 0),
    (np.array([1, 0, 1]), 0),
    (np.array([1, 1, 1]), 1),
]

w = np.random.rand(3)
print(w)

errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = random.choice(training_data)

    result = np.dot(w, x)
    error = expected - step_function(result) # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                     # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x


for x, _ in training_data:
    result = np.dot(w, x)
    print("{}: {} -> {}".format(x, result, step_function(result)))

print(w)

[0.24787614 0.7661357  0.33355738]
[0 0 1]: 33.233557377076856 -> 0
[0 1 1]: 66.89969307996412 -> 0
[1 0 1]: 66.38143351264566 -> 0
[1 1 1]: 100.04756921553292 -> 1
[33.14787614 33.6661357  33.23355738]


In [58]:
step_function = lambda x: 0 if x < 100 else 1         # step function with threshold of 100. Any thing below is 0

# OR Gate
training_data = [
    (np.array([0, 0, 1]), 0),
    (np.array([0, 1, 1]), 1),
    (np.array([1, 0, 1]), 1),
    (np.array([1, 1, 1]), 1),
]

w = np.random.rand(3)
print(w)

errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = random.choice(training_data)

    result = np.dot(w, x)
    error = expected - step_function(result) # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                     # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x


for x, _ in training_data:
    result = np.dot(w, x)
    print("{}: {} -> {}".format(x, result, step_function(result)))

print(w)

[0.82880545 0.40301511 0.78088618]
[0 0 1]: 61.980886179132376 -> 0
[0 1 1]: 100.6839012888509 -> 1
[1 0 1]: 100.10969162497213 -> 1
[1 1 1]: 138.81270673469064 -> 1
[38.12880545 38.70301511 61.98088618]


In [61]:
step_function = lambda x: 0 if x < 100 else 0 if x > 200 else 1         # step function with threshold of 100. Any thing below is 0

# XOR Gate
training_data = [
    (np.array([0, 0, 1]), 0),
    (np.array([0, 1, 1]), 1),
    (np.array([1, 0, 1]), 1),
    (np.array([1, 1, 1]), 0),
]

w = np.random.rand(3)
print(w)

errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = random.choice(training_data)

    result = np.dot(w, x)
    error = expected - step_function(result) # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                     # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x


for x, _ in training_data:
    result = np.dot(w, x)
    print("{}: {} -> {}".format(x, result, step_function(result)))

print(w)

[0.9673341  0.19305423 0.84086284]
[0 0 1]: 99.84086283680469 -> 0
[0 1 1]: 99.833917066734 -> 0
[1 0 1]: 99.80819693438204 -> 0
[1 1 1]: 99.80125116431137 -> 0
[-3.26659024e-02 -6.94577007e-03  9.98408628e+01]


In [64]:
step_function(201)

0