In [ ]:
# importing torch library
import torch

In [ ]:
# initializing a 2d tensor
a = torch.tensor([[1,1], [1,1]], dtype=torch.float)
a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# performing operations on the tensor
b = a + 5
print(b)

tensor([[6., 6.],
        [6., 6.]])


In [ ]:
# performing another operation
c = b.mean()
print(c)

tensor(6.)


### Operations we have applied



1. First of all, we added 5 to all the elements of this tensor
2. Then, we took the mean of that tensor

We performed the following operations on a:

b = a + 5

c = mean(b) = Σ(a+5) / 4






### Gradient of c with respect to a

dc / da = dc/db * db / da = 1/4(1+0) * (1+0) = 1/4 = 0.25

Similarly, we can compute for all elements of a

## Automatic Differentiation

In [ ]:
# initializing a 2d tensor and setting requires_grad as True
a = torch.tensor([[1,1], [1,1]], dtype= torch.float, requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
# performing operations on the tensor
b = a + 5
c = b.mean()
print(b)
print(c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor(6., grad_fn=<MeanBackward0>)


In [ ]:
# back propagating
c.backward()

In [ ]:
# calculated gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
