In [ ]:
import numpy as np
import scipy.linalg as la



### Creation of Vectors and Matrices

1. Create a row vector and a column vector of natural numbers of size 6.

In [ ]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

### Row Vector

The shape and type of the vectors can be checked using array_name.shape and type(array_name)

In [ ]:
x.shape

(6,)

In [ ]:
type(x)

numpy.ndarray

### Column Vector

2. Create a 3 x 3 matrix of all zeros, all ones, all with a value of 5 and all with random values.

In [ ]:
#Zero_matrix
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Ones_matrix
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Matrix_with_value_5
fives = np.full((3,3),5)
fives

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#Random_matrix
random = np.random.rand(3,3)
random

array([[0.81505652, 0.3641909 , 0.43925054],
       [0.01587142, 0.53554234, 0.06034028],
       [0.51258157, 0.10525168, 0.40412741]])

3. a. Create a 3 x 2 matrix using an array of lists and print the type of the array.

   b. Create a 2 x 5 matrix using an array of lists and print the type of the array.

In [ ]:
#3x2_matrix
l1 = [[1,2],[3,4],[5,6]]
mat_1 = np.array(l1)
print(mat_1)
type(mat_1)

[[1 2]
 [3 4]
 [5 6]]


numpy.ndarray

In [ ]:
#2x5_matrix
l2 = [[1,2,3,4,5],[6,7,8,9,0]]
mat_2 = np.array(l2)
print(mat_2)
type(mat_2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


numpy.ndarray

# Vector and Matrix Operations 


4. Find the magnitude/ L1 and L2 norm of the vector [2,3] and state which has has a highest value.


In [ ]:
u = np.array([2,3])
u

array([2, 3])

In [ ]:
L1 = np.linalg.norm(u,ord=1)          #Manhattan_distance
L1

5.0

In [ ]:
L2 = np.linalg.norm(u,ord=2)         #Euclidean_distance
L2

3.605551275463989

In [ ]:
## The Manhattan distance as the highest value

## Vector and Matrix Arithmetic 

5. Perform addition, subtraction, multiplication and division of two matrices of size (3 x 3)

In [ ]:
A = np.random.randint(100,200,size=(3,3))
B = np.random.randint(50,100,size=(3,3))
print(A,B)

[[156 158 198]
 [183 141 153]
 [142 184 169]] [[54 56 95]
 [64 66 82]
 [65 95 82]]


In [ ]:
#Addition
A+B

array([[210, 214, 293],
       [247, 207, 235],
       [207, 279, 251]])

In [ ]:
#Subtraction
A-B

array([[102, 102, 103],
       [119,  75,  71],
       [ 77,  89,  87]])

In [ ]:
#Multiplication
A*B

array([[ 8424,  8848, 18810],
       [11712,  9306, 12546],
       [ 9230, 17480, 13858]])

In [ ]:
#Division
A/B

array([[2.88888889, 2.82142857, 2.08421053],
       [2.859375  , 2.13636364, 1.86585366],
       [2.18461538, 1.93684211, 2.06097561]])

## Dot product

6. Find the dot product of the matrices created above.

In [ ]:
np.dot(A,B)

array([[31406, 37974, 44012],
       [28851, 34089, 41493],
       [30429, 36151, 42436]])

### Scalar and Vector Projections
7. Find the scalar and vector projections of the vector  u = 8i + 6j on vector v = i - 7j


In [ ]:
u = np.array([8,6])
v = np.array([1,-7])
print(u,v)

[8 6] [ 1 -7]


In [ ]:
Scalar = np.dot(u,v)/np.linalg.norm(v)
print('Scalar projection of vector 8i+6j on vector i-7j is', Scalar)

Scalar projection of vector 8i+6j on vector i-7j is -4.808326112068523


In [ ]:
Vector = (v*Scalar)/np.linalg.norm(v)
print('Vector projection of vector 8i+6j on vector i-7j is', Vector)

Vector projection of vector 8i+6j on vector i-7j is [-0.68  4.76]


#### Transpose of a matrix

8. Create the transpose of the 3*3 matrix created above. 

The matrix changes shape such that the rows become columns and columns become rows.

In [ ]:
print(A)
np.transpose(A)

[[156 158 198]
 [183 141 153]
 [142 184 169]]


array([[156, 183, 142],
       [158, 141, 184],
       [198, 153, 169]])

### Identity Matrix

9. Create a 3*3 identity matrix.

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Types of Matrices

10. Create a square matrix of size 3x3 and print 
a. upper triangular matrix
b. lower triangular matrix
c. diagonal matrix



In [ ]:
print(A)
lower = np.tril(A)
lower

[[156 158 198]
 [183 141 153]
 [142 184 169]]


array([[156,   0,   0],
       [183, 141,   0],
       [142, 184, 169]])

In [ ]:
print(A)
upper = np.triu(A)
upper

[[156 158 198]
 [183 141 153]
 [142 184 169]]


array([[156, 158, 198],
       [  0, 141, 153],
       [  0,   0, 169]])

In [ ]:
print(A)
diag = np.diag(A)
diag

[[156 158 198]
 [183 141 153]
 [142 184 169]]


array([156, 141, 169])