In [1]:
import numpy as np

In [10]:
A = np.array([5,6,2,4,7,19,0,3,12]).reshape(3,3)

In [11]:
B = np.array([14,4,5]).reshape(3,1)

array([[14],
       [ 4],
       [ 5]])

In [12]:
C = np.array([1,2,3]).reshape(1,3)
C

array([[1, 2, 3]])

In [13]:
D = np.array([1,2,3,4]).reshape(2,2)
D

array([[1, 2],
       [3, 4]])

In [18]:
I3 = np.identity(3)

In [19]:
print(np.linalg.det(A+I3))

-5.999999999999998


In [20]:
print(np.dot(B,C))

[[14 28 42]
 [ 4  8 12]
 [ 5 10 15]]


In [21]:
print(np.dot(A,B))

[[104]
 [179]
 [ 72]]


In [22]:
print(np.dot(A,A))

[[ 49  78 148]
 [ 48 130 369]
 [ 12  57 201]]


In [24]:
I2 = np.identity(2)

In [25]:
print(np.dot(D,D)-5*D-2*I2)

[[0. 0.]
 [0. 0.]]


In [27]:
###2

In [32]:
u1= np.array([1,7,9])
u2= np.array([3,4,5])
u3= np.array([1,2,1])
v1=np.copy(u1)

v1 / np.linalg.norm(v1)

array([0.08737041, 0.61159284, 0.78633365])

In [29]:
v2= u2-      (         np.dot(u2,v1) / (np.linalg.norm(v1)       )          **2)*v1

131

In [33]:
Z = np.array([[0.08737041, 0.61159284, 0.78633365],
[ 0.99552721, -0.02512372, -0.09107347],
[-0.03594426,  0.79077367, -0.61105238]])

In [41]:
if np.allclose(np.dot(Z,Z.T),np.eye(3)):
    print("Orthogonal")

Orthogonal


In [35]:
E = np.array([[1,7,9],[3,4,5],[1,2,1]])

In [36]:
Q, R = np.linalg.qr(E)

In [37]:
Q

array([[-0.30151134,  0.94684333, -0.11215443],
       [-0.90453403, -0.32125042, -0.28038608],
       [-0.30151134,  0.01690792,  0.95331266]])

In [40]:
if np.allclose(np.dot(Q,Q.T),np.eye(3)):
    print("Orthogonal")

Orthogonal


In [42]:
Z

array([[ 0.08737041,  0.61159284,  0.78633365],
       [ 0.99552721, -0.02512372, -0.09107347],
       [-0.03594426,  0.79077367, -0.61105238]])

In [43]:
Q

array([[-0.30151134,  0.94684333, -0.11215443],
       [-0.90453403, -0.32125042, -0.28038608],
       [-0.30151134,  0.01690792,  0.95331266]])

In [46]:
u1 = np.array([ 0.08737041,  0.61159284,  0.78633365])
u2 = np.array([ 0.99552721, -0.02512372, -0.09107347])
u3 = np.array([-0.03594426,  0.79077367, -0.61105238])

In [47]:
np.dot(u1,u2)

-8.455742086892062e-10

In [48]:
np.dot(u1,u3)

1.5925892787168297e-09

In [49]:
np.dot(u2,u3)

-4.543408398222307e-09