In [1]:
import json

In [7]:
with open("./DataSet/Sarcasm_Headlines_Dataset_v2.json", "r") as f:
    datastore = json.load(f)

In [8]:
sentences = []
labels = []
urls = []

In [11]:
datastore = datastore['A']

In [12]:
for item in datastore:
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])

In [14]:
sentences

['thirtysomething scientists unveil doomsday clock of hair loss',
 'dem rep. totally nails why congress is falling short on gender, racial equality',
 'eat your veggies: 9 deliciously different recipes',
 'inclement weather prevents liar from getting to work',
 "mother comes pretty close to using word 'streaming' correctly",
 'my white inheritance',
 '5 ways to file your taxes with less stress',
 "richard branson's global-warming donation nearly as much as cost of failed balloon trips",
 'shadow government getting too large to meet in marriott conference room b',
 'lots of parents know this scenario',
 'this lesbian is considered a father in indiana (and an amazing one at that)',
 "amanda peet told her daughter sex is 'a special hug'",
 'what to know regarding current treatments for ebola',
 "chris christie suggests hillary clinton was to blame for boko haram's kidnapping of hundreds of schoolgirls",
 'ford develops new suv that runs purely on gasoline',
 'uber ceo travis kalanick step

# Preprocessing

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
len(sentences)

28619

In [23]:
training_size = 20000

training_sentences = sentences[:training_size]
test_sentences = sentences[training_size:]

training_label = labels[:training_size]
test_labels = labels[training_size:]

In [58]:
max_length = 1000

In [60]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

In [62]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences, padding='post',maxlen=max_length)

print(padded[0])
print(padded.shape)

[16004   355  3167  7474  2644     3   661  1119     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0]
(28619, 152)


In [63]:
test_sequences = tokenizer.texts_to_sequences(test_sentences)
test_padded = pad_sequences(test_sequences, padding='post')

# Model Building

In [28]:
import tensorflow as tf

In [64]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(max_length,128),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ])


In [65]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [68]:
history = model.fit(training_padded, training_label, epochs=30,validation_data=(test_padded,test_labels))

ValueError: Unrecognized data type: x=[[12941   325  3169 ...     0     0     0]
 [ 5818  1723   735 ...     0     0     0]
 [  920    36  9074 ...     0     0     0]
 ...
 [ 1358   335  2673 ...     0     0     0]
 [   39   131   113 ...     0     0     0]
 [ 1692  5003  3538 ...     0     0     0]] (of type <class 'numpy.ndarray'>)

In [49]:
training_padded.shape

(20000, 152)