In [1]:
from scipy import stats

# Linear Regrassion Model

In [2]:
years = [0,5,10,15, 20, 25, 30, 35]

In [3]:
salary = [8.4, 9.1, 10.8, 12.3, 15.6, 18.2, 24.7, 25.4]

In [5]:
stats.linregress(years, salary)

LinregressResult(slope=0.5297619047619048, intercept=6.291666666666666, rvalue=0.9693360501716467, pvalue=7.043401672175042e-05, stderr=0.05482828964528311, intercept_stderr=1.1468159567360137)

In [6]:
slope, intercept, r_value, p_value, std_error, intercept = stats.linregress(years, salary)

ValueError: not enough values to unpack (expected 6, got 5)

In [7]:
slope, intercept, r_value, p_value, std_error= stats.linregress(years, salary)

In [8]:
print(slope)
print(intercept)
print(r_value)
print(p_value)
print(std_error)

0.5297619047619048
6.291666666666666
0.9693360501716467
7.043401672175042e-05
0.05482828964528311


In [10]:
#y = mx + c
year = 45

In [11]:
slope*year + intercept

30.13095238095238

# Error Calculation

In [12]:
slope*0 + intercept

6.291666666666666

In [13]:
import numpy as np

In [16]:
slope * np.array(years) + intercept

# salary = [8.4, 9.1, 10.8, 12.3, 15.6, 18.2, 24.7, 25.4]    - Actual Value

array([ 6.29166667,  8.94047619, 11.58928571, 14.23809524, 16.88690476,
       19.53571429, 22.18452381, 24.83333333])

In [19]:
slope * np.array(years) + intercept - np.array(salary)

array([-2.10833333, -0.15952381,  0.78928571,  1.93809524,  1.28690476,
        1.33571429, -2.51547619, -0.56666667])

In [20]:
error = slope * np.array(years) + intercept - np.array(salary)

In [21]:
sum(abs(error))

10.69999999999999

In [31]:
p = np.array([[80, 40, 120],[60,30,120]])

In [32]:
print(p)

[[ 80  40 120]
 [ 60  30 120]]


In [34]:
q = np.array([[1/2,1/5],[1/4,1/5],[1/4,3/5]])

In [35]:
np.dot(p,q)

array([[80. , 96. ],
       [67.5, 90. ]])

# Linear Equations

In [36]:
# 0.2*x + 0.5*y + 0.3*z = 1950
# 0.3*x + 0.4*y + 0.1*z = 1490
# 0.1*x + 0.6*y + 0.4*z = 2160

In [41]:
import sympy as sym
sym.init_printing()
x, y, z = sym.symbols('x,y,z')

sym.solve([0.2*x + 0.5*y + 0.3*z - 1950,
          0.3*x + 0.4*y + 0.1*z - 1490,
          0.1*x + 0.6*y + 0.4*z - 2160],[x,y,z])

In [43]:
dict1 = sym.solve([0.2*x + 0.5*y + 0.3*z - 1950,
          0.3*x + 0.4*y + 0.1*z - 1490,
          0.1*x + 0.6*y + 0.4*z - 2160],[x,y,z])

In [45]:
print(dict1)
print(type(dict1))

{x: 2000.00000000000, y: 1600.00000000000, z: 2500.00000000000}
<class 'dict'>


In [48]:
from scipy import linalg

In [ ]:
"""
      x + 2*y + 3*z = 18
    3*x +   y + 2*z = 23
    2*x       +   z = 13
"""

In [49]:
a = np.array([[1,2,3],[3,1,2],[2,0,1]])
b = np.array([18,23,13])

np.dot(linalg.inv(a),b)

array([5., 2., 3.])