# Gradient Descent

In [1]:
import numpy as np

In [2]:
def f(x):
    return x**2 - 2

In [9]:
def slopeFunction(f, x, h=0.1):
    numerator = f(x+h) - f(x)
    denominator = h
    return numerator/denominator
    

In [10]:
def gradDesc(XOld, slope, alpha=0.1):
    XNew = XOld - alpha*slope
    return XNew

In [16]:
X0 = -1

XOld = X0; XOldTemp = XOld; XNew = 0; i = 0
while (abs(XNew - XOldTemp) > 0.001):
    XOldTemp = XOld
    slope = slopeFunction(f, XOld, 0.1)
    XNew = gradDesc(XOld, slope)
    print(np.round((XNew, slope, f(XNew), i), 2))
    XOld = XNew
    i = i + 1

print('Iteration', i)

[-0.81 -1.9  -1.34  0.  ]
[-0.66 -1.52 -1.57  1.  ]
[-0.54 -1.22 -1.71  2.  ]
[-0.44 -0.97 -1.81  3.  ]
[-0.36 -0.78 -1.87  4.  ]
[-0.3  -0.62 -1.91  5.  ]
[-0.25 -0.5  -1.94  6.  ]
[-0.21 -0.4  -1.96  7.  ]
[-0.18 -0.32 -1.97  8.  ]
[-0.15 -0.26 -1.98  9.  ]
[-0.13 -0.2  -1.98 10.  ]
[-0.12 -0.16 -1.99 11.  ]
[-0.1  -0.13 -1.99 12.  ]
[-0.09 -0.1  -1.99 13.  ]
[-0.08 -0.08 -1.99 14.  ]
[-0.08 -0.07 -1.99 15.  ]
[-0.07 -0.05 -1.99 16.  ]
[-0.07 -0.04 -2.   17.  ]
[-0.06 -0.03 -2.   18.  ]
[-0.06 -0.03 -2.   19.  ]
[-0.06 -0.02 -2.   20.  ]
[-6.0e-02 -2.0e-02 -2.0e+00  2.1e+01]
[-6.0e-02 -1.0e-02 -2.0e+00  2.2e+01]
[-5.0e-02 -1.0e-02 -2.0e+00  2.3e+01]
[-5.0e-02 -1.0e-02 -2.0e+00  2.4e+01]
Iteration 25
