In [83]:
pip install session-info

  Using cached session_info-1.0.0.tar.gz (24 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached stdlib_list-0.10.0-py3-none-any.whl.metadata (3.3 kB)
   ---------------------------------------- 0.0/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/79.8 kB ? eta -:--:--


In [85]:
import numpy as np
import scipy.linalg as la
import math

import session_info
session_info.show()


## Session 1 

### Creation of Vectors and Matrices

1. Create a row vector of natural numbers of size 4.

In [20]:
row_vector = np.random.randint(10, size=(4))
row_vector

array([6, 4, 8, 0])

2. Create a 2 x 2 matrix of all zeros, all ones, all with a value of 4 and all with random values.

In [25]:
mat_0 = np.zeros((2,2),int)
mat_0

array([[0, 0],
       [0, 0]])

In [26]:
mat_1 = np.ones((2,2),int)
mat_1

array([[1, 1],
       [1, 1]])

In [32]:
mat_4 = np.ones((2,2),int) * 4
mat_4

array([[4, 4],
       [4, 4]])

In [35]:
mat_r = np.random.randint(10, size=(4)).reshape((2,2))
mat_r

array([[0, 3],
       [9, 3]])

### Vector and Matrix Operations 


3. Find the magnitude/ L1 and L2 norm of the vector [4,6] and state which has a highest value.


In [39]:
a = [4,6]
L1 = np.linalg.norm(a,1)
L2 = np.linalg.norm(a)

print("L1 Norm : ",L1)
print("L2 Norm : ",L2)


L1 Norm :  10.0
L2 Norm :  7.211102550927978


### Scalar and Vector Projections
5. Find the scalar and vector projections of the vector  u = 8i + 6j on vector v = i - 7j


In [42]:
u = np.array([8,6])
v = np.array([1,-7])

v_norm = np.sqrt(sum(v**2))

scalar_projection = (np.dot(u,v)) / v_norm

vector_projection = (np.dot(u,v) * v ) / sum(v**2)

print("Scalar Projection : ", scalar_projection)

print("Vector Projection : ", vector_projection)

Scalar Projection :  -4.808326112068523
Vector Projection :  [-0.68  4.76]


### Session 2



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL  import Image
import scipy
from skimage import data
from numpy import *


#### Q5. Find the Determinant for the following matrix. If B is a scaled matrix computed by scaling the matrix A, find the scale factor associated.

In [52]:
A = np.array([
[10, 12, 13],
[14, 15, 16],
[17, 18, 19]])

In [53]:
B=np.array([
[30, 36, 39],
[42, 45, 48],
[51, 54, 57]])

In [80]:
def checkScalingFactor(A, B):
    """
        This function will check if Matrix B is a scaled version of Matrix A
        If yes, it will print the scaling factorr
    """
    #check shape of both of the matrices and if they are equivalent
    
    # Find determinant for both of the matrices
    A_det = np.number.round(np.linalg.det(A))
    B_det = np.number.round(np.linalg.det(B))

    # size  of the square matrix
    degree = A.shape[0]

    #Enclosed Space in A is A_det units power degree where as in B it is B_det power degree
    #divide B_det / A_det, and it should provide, howmuch is the enclosed space stretched.
    # also, degreeth root needs to be calculated for single line scaling or stretching
    scaling_Factor = math.pow((B_det / A_det),( 1 / degree) )

    # if the resultant matrix does not disturb the figure(stretched and not transformed), then it must be a scalar multiplication of initial matrix
    if np.all( B == (scaling_Factor * A)):
        print("Matrix B is scaled by : ", scaling_Factor)
    else:
        print("it is not scaled")

In [81]:
checkScalingFactor(A,B)

Matrix B is scaled by :  3.0


#### Q6: If Matrix A and B are given, then find the matrix X from AX=B. 

In [86]:
A = np.array([
[11, 12, 13],
[11, 15, 14],
[17, 11, 19]])

B = np.array([[1, -1 , 1],[1, -1 , 1],[1, -1 , 1]])

In [87]:
X=np.linalg.solve(A,B)
X

array([[ 0.40425532, -0.40425532,  0.40425532],
       [ 0.12765957, -0.12765957,  0.12765957],
       [-0.38297872,  0.38297872, -0.38297872]])

### System of Linear equations

#### Q7. Solve the following system and find x and y $$\begin{pmatrix}
1&2\\
3&4
\end{pmatrix} \begin{pmatrix}
x\\
y
\end{pmatrix} =\begin{pmatrix}
-1\\
1
\end{pmatrix}$$

In [96]:
A = [[1,2],[3,4]]
B = [[-1],[1]]
X=np.linalg.solve(A,B)
print("x : ",X[0][0]," y : ",np.number.round(X[1][0]))

x :  3.0  y :  -2.0


### Gram-Schmidt Process

#### Q8.Convert the following matrix to an orthogonal matrix using Gram Schmidt Process?
\begin{align}
B = \begin{bmatrix}
12 & 13 & 14\\
13 & 14 & 15\\
15 & 16 & 13
\end{bmatrix}
\end{align}

In [118]:
B = np.array([[12,13,14],[13,14,15],[15,16,13]])


def gram_smit(B):
    Q,R = np.linalg.qr(B)
    return Q, R
Q, R = gram_smit(B)

if np.allclose(np.dot(Q,Q.T),np.eye(3)):
    print("Q : is a Orthogonal Matrix\n",Q)


Q : is a Orthogonal Matrix
 [[-0.51735674  0.66830212  0.53452248]
 [-0.5604698   0.20740411 -0.80178373]
 [-0.64669592 -0.71439192  0.26726124]]


In [15]:
#hint: To check if a given matrix is orthogonal, first find the transpose of that matrix. Then, multiply the given matrix with the transpose. 
#Now, if the product is an identity matrix, the given matrix is orthogonal, otherwise, not.

### Eigen values 

#### Q9.Find eigen values and eigen vectors for 

\begin{align}
A = \begin{bmatrix}
2 & -1 & 0\\
-1 & 2 & -1\\
0 & -1 & 2
\end{bmatrix}
\end{align}

In [51]:
A = np.array([
[2, -1, 0],
[-1, 2, -1],
[0, -1, 2]])

w, v = np.linalg.eig(A)
print("Eigen Value for Matrix A is : \n", w)
print()
print("Eigen Vector for Matrix A is : \n", v)


Eigen Value for Matrix A is : 
 [3.41421356 2.         0.58578644]

Eigen Vector for Matrix A is : 
 [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  5.09486455e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
